### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by alexander-deb69** [SardorLut/Tanchiki_pygame#4]
У тебя точно все это используется? Чем ты его сгенерировал? В файле должно быть только те пакеты, которых нет в стандартной библиотеке питона и которые нужно доставить

**Comment by SardorLut** [comment]
ну у меня этот листик создался. По инструкции все делал

**Comment by alexander-deb69** [comment]
Я понимаю, в этом и проблема автоматической генерации... Там много лишнего
